- name: Terminate AWS instances
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
     instance_ids:
      - '\\*Your aws instance id*\\'

  tasks:

    - name: Terminate instances that were previously launched
      ec2:
        instance_ids: '{{ instance_ids }}'
        state: 'absent'
        region: \\*Your aws region*\\
        aws_access_key: \\*Your aws access key*\\
        aws_secret_key: \\*Your aws secret key*\\
